misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = true
  # set vrr per monitor
  always_follow_on_dnd = true
  allow_session_lock_restore = true
  on_focus_under_fullscreen = 1
  initial_workspace_tracking = 2
}

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

xwayland {
  enabled = true
  force_zero_scaling = true
}
