alias sudo='sudo '
alias ..='z ..'
alias cd='z'
alias c='clear'
alias ff='fastfetch'
alias ls='eza -a --icons=always'
alias ll='eza -al --icons=always'
alias lt='eza -a --tree --level=1 --icons=always'
alias e='$EDITOR'
alias settings='ml4w-dotfiles-settings org.singularity.dotfiles'
