[control_center]
hidden_tabs = []
show_session_button = true
show_shortcut_labels = true
sidebar = "compact"
sidebar_section = "compact"
width = 700

[control_center.calendar]
show_events_card = true
show_week_numbers = false

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"
