; noctalia.ini
[base]
default          = {{colors.on_surface.default.hex}}
unknown-token    = {{colors.error.default.hex}},bold
commandseparator = {{colors.tertiary_fixed.default.hex}}
redirection      = {{colors.tertiary_fixed.default.hex}}
here-string-tri  = {{colors.on_surface_variant.default.hex}}
here-string-text = {{colors.on_surface_variant.default.hex}}
here-string-var  = {{colors.on_surface_variant.default.hex}}
exec-descriptor  = none
comment          = {{colors.on_surface_variant.default.hex}}
correct-subtle   = {{colors.primary_fixed_dim.default.hex}}
incorrect-subtle = {{colors.error.default.hex}}
subtle-separator = none
subtle-bg        = none
secondary        =
recursive-base   = {{colors.on_surface.default.hex}}

[command-point]
reserved-word     = {{colors.primary_fixed.default.hex}}
subcommand        = {{colors.tertiary.default.hex}}
alias             = {{colors.primary.default.hex}}
suffix-alias      = {{colors.primary.default.hex}}
global-alias      = {{colors.primary.default.hex}}
builtin           = {{colors.primary_fixed.default.hex}}
function          = {{colors.primary.default.hex}}
command           = {{colors.primary.default.hex}}
precommand        = {{colors.primary_fixed.default.hex}}
hashed-command    = {{colors.primary.default.hex}}
single-sq-bracket = {{colors.primary.default.hex}}
double-sq-bracket = {{colors.primary.default.hex}}
double-paren      = {{colors.tertiary_fixed.default.hex}}

[paths]
path          = {{colors.secondary_fixed_dim.default.hex}}
pathseparator = {{colors.secondary_fixed_dim.default.hex}}
path-to-dir   = {{colors.secondary_fixed_dim.default.hex}},underline
globbing      = {{colors.primary_fixed_dim.default.hex}}
globbing-ext  = none

[brackets]
paired-bracket  = bold
bracket-level-1 = {{colors.primary.default.hex}}
bracket-level-2 = {{colors.secondary.default.hex}}
bracket-level-3 = {{colors.tertiary.default.hex}}

[arguments]
single-hyphen-option   = {{colors.secondary.default.hex}}
double-hyphen-option   = {{colors.secondary.default.hex}}
back-quoted-argument   = {{colors.secondary.default.hex}}
single-quoted-argument = none
double-quoted-argument = {{colors.tertiary_fixed.default.hex}}
dollar-quoted-argument = {{colors.tertiary_fixed.default.hex}}
optarg-string          = {{colors.tertiary_fixed.default.hex}}
optarg-number          = {{colors.secondary_fixed.default.hex}}

[in-string]
back-dollar-quoted-argument           = {{colors.secondary_fixed.default.hex}}
back-or-dollar-double-quoted-argument = {{colors.secondary_fixed.default.hex}}

[other]
variable             = {{colors.secondary_fixed.default.hex}}
assign               = none
assign-array-bracket = none
history-expansion    = none

[math]
mathvar =
mathnum = {{colors.secondary_fixed.default.hex}}
matherr = {{colors.error.default.hex}},bold

[for-loop]
forvar  = {{colors.on_surface.default.hex}}
fornum  = {{colors.secondary_fixed.default.hex}}
foroper = {{colors.primary.default.hex}}
forsep  = {{colors.primary.default.hex}}

[case]
case-input       = {{colors.secondary_fixed.default.hex}}
case-parentheses = {{colors.on_surface_variant.default.hex}}
case-condition   = underline
