gestures {
  workspace_swipe_create_new = false
}

gesture = 3, horizontal, workspace

# Lock screen before suspend
bindl = , switch:on:Lid Switch, exec, qs -c noctalia-shell ipc call lockScreen lock
