[bar]
order = ["default"]

[bar.default]
auto_hide = false
background_opacity = 0.0
border = "outline"
border_width = 0.0
capsule = true
capsule_fill = "surface_variant"
capsule_group = []
capsule_opacity = 1.0
capsule_padding = 6.0
capsule_thickness = 0.75999999046325684
center = ["workspaces"]
concave_edge_corners = true
contact_shadow = false
enabled = true
end = ["input_volume", "volume", "network", "bluetooth", "brightness", "battery", "tray", "clock", "notifications", "system-upgrade", "control-center"]
font_weight = 500
hover_highlight = true
layer = "top"
margin_edge = 0
margin_ends = 10
margin_opposite_edge = 0
padding = 0
panel_overlap = 1
position = "top"
radius = 12
radius_bottom_left = 12
radius_bottom_right = 12
radius_top_left = 12
radius_top_right = 12
reserve_space = true
scale = 1.0
shadow = false
show_on_workspace_switch = true
smart_auto_hide = false
start = ["launcher", "taskbar", "active_window"]
thickness = 34
widget_spacing = 6

[bar.default.dead_zone]
