[osd]
background_opacity = 0.97000002861022949
border = true
enabled = true
monitors = []
offset_x = 20
offset_y = 8
orientation = "horizontal"
position = "top_right"
position_vertical = "top_center"
scale = 1.0

[osd.kinds]
bluetooth = true
brightness = true
caffeine = true
dnd = true
keyboard_backlight = true
keyboard_layout = true
lock_keys = true
media = true
nightlight = true
power_profile = true
privacy = true
volume = true
volume_input = true
volume_output = true
wifi = true
