[idle]
behavior_order = ["lock", "screen-off", "lock-and-suspend"]
pre_action_fade_seconds = 5.0

[idle.behavior.lock]
action = "lock"
command = ""
enabled = true
resume_command = ""
timeout = 600.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
command = ""
enabled = true
resume_command = ""
timeout = 900.0

[idle.behavior.screen-off]
action = "screen_off"
command = ""
enabled = true
resume_command = ""
timeout = 660.0
